In [1]:
import py_dss_interface
from py_dss_toolkit import dss_tools


dss_file = r"C:\Dados_teste\OpenDSS\GWO\Alim_Meia_Ponte_5_REDUZIDO\Master_PyDSS_Interface.dss"

dss = py_dss_interface.DSS()

dss_tools.update_dss(dss)

dss.text(f"compile [{dss_file}]")

dss.text(f"buscoords BusCoords.csv")

dss.text("set mode=daily")
dss.text("set stepsize=1h")
dss.text("set number=24")

dss.solution.solve()

dss.monitors.name = "feeder"
monitor_list = dss.monitors.channel(1)
print(monitor_list)

df = dss_tools.results.monitor("feeder")
display(df)

energymeter_df = dss_tools.results.energymeters
display(energymeter_df)

[1530.3839111328125, 1400.0325927734375, 1308.851806640625, 1290.020263671875, 1277.712158203125, 1333.8037109375, 1422.369873046875, 1386.5621337890625, 1471.7667236328125, 1611.1793212890625, 1653.4090576171875, 1784.3017578125, 1892.021728515625, 1795.1837158203125, 1828.23681640625, 1803.792236328125, 1846.59033203125, 1945.88134765625, 2290.089111328125, 2354.4111328125, 2310.54638671875, 2190.955078125, 1953.5897216796875, 1778.087158203125]

,Hour,sec,P1 (kW),Q1 (kvar),P2 (kW),Q2 (kvar),P3 (kW),Q3 (kvar)
0,1.0,0.0,1530.383911,739.098389,1531.776733,739.532532,1530.509033,739.051758
1,2.0,0.0,1400.032593,662.299316,1401.311035,662.694397,1400.136841,662.260620
2,3.0,0.0,1308.851807,610.360779,1310.050781,610.728516,1308.942749,610.327271
3,4.0,0.0,1290.020264,599.788391,1291.202759,600.150452,1290.108521,599.755859
4,5.0,0.0,1277.712158,592.773315,1278.883911,593.131592,1277.798584,592.741455
5,6.0,0.0,1333.803711,623.909363,1335.024292,624.284119,1333.898071,623.874451
6,7.0,0.0,1422.369873,674.715881,1423.667725,675.117249,1422.477417,674.675964
7,8.0,0.0,1386.562134,653.989990,1387.828735,654.380554,1386.664307,653.952148
8,9.0,0.0,1471.766724,705.027893,1473.108032,705.445190,1471.882324,704.984924
9,10.0,0.0,1611.179321,790.867859,1612.643555,791.328430,1611.318726,790.815796
10,11.0,0.0,1653.409058,817.750061,1654.910645,818.223938,1653.556274,817.695068
11,12.0,0.0,1784.301758,900.616028,1785.919922,901.128784,1784.474365,900.551453
12,13.0,0.0,1892.021729,972.601318,1893.736572,973.147278,1892.217285,972.528198
13,14.0,0.0,1795.183716,909.816345,1796.811768,910.334229,1795.358765,909.750854
14,15.0,0.0,1828.236816,932.236755,1829.894409,932.765198,1828.418823,932.168640
15,16.0,0.0,1803.792236,916.313660,1805.427856,916.834839,1803.969116,916.247437
16,17.0,0.0,1846.590332,943.481506,1848.264404,944.014771,1846.776123,943.411987
17,18.0,0.0,1945.881348,1008.020386,1947.644531,1008.581726,1946.088745,1007.942810
18,19.0,0.0,2290.089111,1267.531250,2292.167480,1268.200317,2290.384277,1267.419312
19,20.0,0.0,2354.411133,1322.355591,2356.550537,1323.046753,2354.725586,1322.236084
20,21.0,0.0,2310.546387,1287.211548,2312.644043,1287.888184,2310.847656,1287.096924
21,22.0,0.0,2190.955078,1186.947266,2192.941650,1187.584717,2191.222900,1186.846558
22,23.0,0.0,1953.589722,1011.167297,1955.359741,1011.729187,1953.798584,1011.089172
23,24.0,0.0,1778.087158,893.221558,1779.699585,893.729614,1778.258179,893.157593

,name,kwh,kvarh,max kw,max kva,zone kwh,zone kvarh,zone max kw,zone max kva,overload kwh normal,...,aux19,aux24,aux29,13.8 kv load energy,aux5,aux10,aux15,aux20,aux25,aux30
0,busa4-_2021126072_segmmt_53951427,124421.081474,63076.686747,7065.687191,8103.461649,118141.936302,49529.463882,6612.56024,7223.772169,107.853497,...,0.0,0.0,0.0,118141.936302,0.0,0.0,0.0,0.0,0.0,0.0

In [2]:
trafo_df = dss_tools.model.transformers_df

display(trafo_df)

,name,phases,windings,wdg,bus,conn,kv,kva,tap,%r,...,bhcurrent,bhflux,normamps,emergamps,faultrate,pctperm,repair,basefreq,enabled,like
0,trf_5286699a,1,3,3,82034475286699.4.2,wye,0.22,10,1.05,0.2,...,[],[],1.3806,1.8827,0.007,100,36,60,true,
1,trf_5286707a,3,2,2,82034835286707.1.2.3.4,wye,0.38,45,1.05,0.7611111,...,[],[],2.0709,2.824,0.007,100,36,60,true,
2,trf_5286708a,1,3,3,82034845286708.4.2,wye,0.22,15,1.05,0.2,...,[],[],2.0709,2.824,0.007,100,36,60,true,
3,trf_5286718a,3,2,2,82053655286718.1.2.3.4,wye,0.38,45,1.05,0.7611111,...,[],[],2.0709,2.824,0.007,100,36,60,true,
4,trf_5286787a,3,2,2,82023305286787.1.2.3.4,wye,0.38,112.5,1.05,0.6088889,...,[],[],5.1773,7.06,0.007,100,36,60,true,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,trf_5333902a,3,2,2,85167275333902.1.2.3.4,wye,0.38,112.5,1.05,0.6088889,...,[],[],5.1773,7.06,0.007,100,36,60,true,
139,trf_5740255a,3,2,2,82056945740255.1.2.3.4,wye,0.38,112.5,1.05,0.6088889,...,[],[],5.1773,7.06,0.007,100,36,60,true,
140,trf_5740270a,3,2,2,96033635740270.1.2.3.4,wye,0.38,75,1.05,0.67,...,[],[],3.4516,4.7067,0.007,100,36,60,true,
141,trf_5744153a,3,2,2,96264655744153.1.2.3.4,wye,0.38,112.5,1.05,0.6088889,...,[],[],5.1773,7.06,0.007,100,36,60,true,
142,trf_5444435a,3,2,2,81481405444435.1.2.3.4,wye,0.38,112.5,1.05,0.6088889,...,[],[],5.1773,7.06,0.007,100,36,60,true,

In [25]:
with open("Monitores_GA.dss", "w", encoding="utf-8") as f:
    f.write("//Feeder\n")
    f.write("New monitor.feeder element='Line.SMT_53951427' terminal=1 mode=1 ppolar=no\n\n")
    f.write("//Trafos\n")

    for trafo in trafo_df["name"]:
        f.write(f"New monitor.{trafo} element='Transformer.{trafo}' terminal=1 mode=1 ppolar=no\n")

In [3]:
loads_df = dss_tools.model.loads_df
display(loads_df)
display(trafo_df)
count = 0
for bus in loads_df["bus1"]:
    trafo_query = trafo_df.query(f"bus == '{bus}'")
    if trafo_query.empty:
        print(bus + "\n")
        count += 1

print(count)

,name,phases,bus1,kv,kw,pf,model,yearly,daily,duty,...,zipv,%seriesrl,relweight,vlowpu,puxharm,xrharm,spectrum,basefreq,enabled,like
0,mt_10009727955_m1,3,88185385002086.1.2.3.4,13.8,5.46925728729341,0.9021,2,,CURVA,,...,,50,1,0.5,0,6,defaultload,60,true,
1,mt_10009727955_m2,3,88185385002086.1.2.3.4,13.8,5.46925728729341,0.9021,3,,CURVA,,...,,50,1,0.5,0,6,defaultload,60,true,
2,mt_10014416466_m1,3,89458365002086.1.2.3.4,13.8,2.65068009244008,0.9021,2,,CURVA,,...,,50,1,0.5,0,6,defaultload,60,true,
3,mt_10014416466_m2,3,89458365002086.1.2.3.4,13.8,2.65068009244008,0.9021,3,,CURVA,,...,,50,1,0.5,0,6,defaultload,60,true,
4,mt_10015559007_m1,3,89813615002086.1.2.3.4,13.8,2.32027223167495,0.9021,2,,CURVA,,...,,50,1,0.5,0,6,defaultload,60,true,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,m1_trf_5333902a,3,85167275333902.1.2.3.4,0.38,26.2254249405443,0.9076,2,,CURVA,,...,,50,1,0.5,0,6,defaultload,60,true,
302,m1_trf_5740255a,3,82056945740255.1.2.3.4,0.38,14.5905864350407,0.9101,2,,CURVA,,...,,50,1,0.5,0,6,defaultload,60,true,
303,m1_trf_5740270a,3,96033635740270.1.2.3.4,0.38,12.2445576749837,0.9097,2,,CURVA,,...,,50,1,0.5,0,6,defaultload,60,true,
304,m1_trf_5744153a,3,96264655744153.1.2.3.4,0.38,16.4320475658323,0.9072,2,,CURVA,,...,,50,1,0.5,0,6,defaultload,60,true,
305,m1_trf_5444435a,3,81481405444435.1.2.3.4,0.38,11.0902798793934,0.9097,2,,CURVA,,...,,50,1,0.5,0,6,defaultload,60,true,

,name,phases,windings,wdg,bus,conn,kv,kva,tap,%r,...,bhcurrent,bhflux,normamps,emergamps,faultrate,pctperm,repair,basefreq,enabled,like
0,trf_5286699a,1,3,3,82034475286699.4.2,wye,0.22,10,1.05,0.2,...,[],[],1.3806,1.8827,0.007,100,36,60,true,
1,trf_5286707a,3,2,2,82034835286707.1.2.3.4,wye,0.38,45,1.05,0.7611111,...,[],[],2.0709,2.824,0.007,100,36,60,true,
2,trf_5286708a,1,3,3,82034845286708.4.2,wye,0.22,15,1.05,0.2,...,[],[],2.0709,2.824,0.007,100,36,60,true,
3,trf_5286718a,3,2,2,82053655286718.1.2.3.4,wye,0.38,45,1.05,0.7611111,...,[],[],2.0709,2.824,0.007,100,36,60,true,
4,trf_5286787a,3,2,2,82023305286787.1.2.3.4,wye,0.38,112.5,1.05,0.6088889,...,[],[],5.1773,7.06,0.007,100,36,60,true,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,trf_5333902a,3,2,2,85167275333902.1.2.3.4,wye,0.38,112.5,1.05,0.6088889,...,[],[],5.1773,7.06,0.007,100,36,60,true,
139,trf_5740255a,3,2,2,82056945740255.1.2.3.4,wye,0.38,112.5,1.05,0.6088889,...,[],[],5.1773,7.06,0.007,100,36,60,true,
140,trf_5740270a,3,2,2,96033635740270.1.2.3.4,wye,0.38,75,1.05,0.67,...,[],[],3.4516,4.7067,0.007,100,36,60,true,
141,trf_5744153a,3,2,2,96264655744153.1.2.3.4,wye,0.38,112.5,1.05,0.6088889,...,[],[],5.1773,7.06,0.007,100,36,60,true,
142,trf_5444435a,3,2,2,81481405444435.1.2.3.4,wye,0.38,112.5,1.05,0.6088889,...,[],[],5.1773,7.06,0.007,100,36,60,true,

88185385002086.1.2.3.4

88185385002086.1.2.3.4

89458365002086.1.2.3.4

89458365002086.1.2.3.4

89813615002086.1.2.3.4

89813615002086.1.2.3.4

90964325002086.1.2.3.4

90964325002086.1.2.3.4

89813615002086.1.2.3.4

89813615002086.1.2.3.4

88185385002086.1.2.3.4

88185385002086.1.2.3.4

89458365002086.1.2.3.4

89458365002086.1.2.3.4

89813615002086.1.2.3.4

89813615002086.1.2.3.4

90964325002086.1.2.3.4

90964325002086.1.2.3.4

89813615002086.1.2.3.4

89813615002086.1.2.3.4

82034475286699.1.2.3.4

82034845286708.1.2.3.4

82034475286699.1.2.3.4

82034845286708.1.2.3.4

24

In [4]:
buses_df = dss_tools.model.buses_df

graph_df = dss_tools.model.graph_df

line_df = dss_tools.model.lines_df

display(buses_df[["name", "distance", "all_pce_active_bus", "all_pde_active_bus"]])
display(graph_df)
display(line_df)
print(buses_df.columns)

,name,distance,all_pce_active_bus,all_pde_active_bus
0,84808465002086,0.000000,[Vsource.source],"[Line.smt_53951427, Line.smt_88888868971, Line..."
1,81463945002086,4.408302,[None],"[Line.cmt_5281595, Line.smt_53072500]"
2,81463945002086b,4.409302,[None],"[Line.cmt_5281595, Line.smt_53001146]"
3,82034695002086,8.158531,[None],"[Line.cmt_5286666, Line.smt_53072619]"
4,82034695002086b,8.159531,[None],"[Line.cmt_5286666, Line.smt_53072618]"
...,...,...,...,...
1212,85167275333902,6.570240,"[Load.m2_trf_5333902a, Load.m1_trf_5333902a, R...",[Transformer.trf_5333902a]
1213,82056945740255,6.754673,"[Load.m2_trf_5740255a, Load.m1_trf_5740255a, R...",[Transformer.trf_5740255a]
1214,96033635740270,7.334388,"[Load.m2_trf_5740270a, Load.m1_trf_5740270a, R...",[Transformer.trf_5740270a]
1215,96264655744153,5.191805,"[Load.m2_trf_5744153a, Load.m1_trf_5744153a, R...",[Transformer.trf_5744153a]
1216,81481405444435,8.158985,"[Load.m2_trf_5444435a, Load.m1_trf_5444435a, R...",[Transformer.trf_5444435a]

,bus1,bus2,name,type,bus1_dss,bus2_dss,nodes1,nodes2,phases,enabled,reversed,num_windings,conns,kvs,kv_primary,kv_secondary,conn_primary,conn_secondary,kv_tertiary,conn_tertiary
0,84808465002086,i888888516545002086,line.smt_88888869403,line,84808465002086,i888888516545002086,"[1, 2, 3]","[1, 2, 3]",3,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,84808465002086,i888888340825002086,line.smt_88888868971,line,84808465002086,i888888340825002086,"[1, 2, 3]","[1, 2, 3]",3,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,84808465002086,82065635002086,line.smt_53951427,line,84808465002086,82065635002086,"[1, 2, 3]","[1, 2, 3]",3,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,81463945002086,81463945002086b,line.cmt_5281595,line,81463945002086,81463945002086b,"[1, 2, 3]","[1, 2, 3]",3,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,81463945002086b,93309575002086,line.smt_53001146,line,81463945002086b,93309575002086,"[1, 2, 3]","[1, 2, 3]",3,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1211,i888888516535002086,i888888516525002086g,line.smt_88888869150,line,i888888516535002086,i888888516525002086g,"[1, 2, 3]","[1, 2, 3]",3,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1212,i888888516545002086,i888888516555002086b,line.smt_88888869152,line,i888888516545002086,i888888516555002086b,"[1, 2, 3]","[1, 2, 3]",3,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1213,i888888516545002086,i888888516535002086,line.smt_88888869151,line,i888888516545002086,i888888516535002086,"[1, 2, 3]","[1, 2, 3]",3,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1214,mrt_82034475002086trf_5286699a,82034475286699,transformer.trf_5286699a,transformer,mrt_82034475002086trf_5286699a,82034475286699,[2],"[1, 4]",1,True,False,3.0,"[wye, wye, wye]","[7.967434, 0.22, 0.22]",7.967434,0.22,wye,wye,0.22,wye
1215,mrt_82034845002086trf_5286708a,82034845286708,transformer.trf_5286708a,transformer,mrt_82034845002086trf_5286708a,82034845286708,[2],"[1, 4]",1,True,False,3.0,"[wye, wye, wye]","[7.967434, 0.22, 0.22]",7.967434,0.22,wye,wye,0.22,wye

,name,bus1,bus2,linecode,length,phases,r1,x1,r0,x0,...,heightunit,conductors,normamps,emergamps,faultrate,pctperm,repair,basefreq,enabled,like
0,cmt_5281595,81463945002086.1.2.3,81463945002086b.1.2.3,,0.001,3,1,1,1,1,...,m,,400,600,0.1,20,3,60,true,
1,cmt_5286666,82034695002086.1.2.3,82034695002086b.1.2.3,,0.001,3,1,1,1,1,...,m,,400,600,0.1,20,3,60,true,
2,cmt_5286668,82034735002086.1.2.3,82034735002086b.1.2.3,,0.001,3,1,1,1,1,...,m,,400,600,0.1,20,3,60,true,
3,cmt_5286669,82044285002086.1.2.3,82044285002086b.1.2.3,,0.001,3,1,1,1,1,...,m,,400,600,0.1,20,3,60,true,
4,cmt_5286671,82054225002086.1.2.3,82054225002086b.1.2.3,,0.001,3,1,1,1,1,...,m,,400,600,0.1,20,3,60,true,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068,smt_88888869158,i888888516555002086.1.2.3,i888888516585002086.1.2.3,39-31m_3,1E-006,3,1.551,0.47,0.1784,0.4047,...,m,,125,600,0.1,20,3,60,true,
1069,smt_88888869403,84808465002086.1.2.3,i888888516545002086.1.2.3,39-31m_3,1E-006,3,1.551,0.47,0.1784,0.4047,...,m,,125,600,0.1,20,3,60,true,
1070,smt_53073787,82041975002086.1.2.3,82041965002086.1.2.3,33-31m_3,0.047869,3,0.975,0.47,0.1784,0.4047,...,m,,152,600,0.1,20,3,60,true,
1071,resist_mtr_trf_5286699a,82034475002086.2,mrt_82034475002086trf_5286699a.2,lc_mrt_trf_5286699a_1,0.001,1,15000,0,15000,0,...,m,,0,600,0.1,20,3,60,true,
1072,resist_mtr_trf_5286708a,82034845002086.2,mrt_82034845002086trf_5286708a.2,lc_mrt_trf_5286708a_1,0.001,1,15000,0,15000,0,...,m,,0,600,0.1,20,3,60,true,

Index(['name', 'nodes', 'num_nodes', 'kv_base', 'distance', 'coord_defined',
       'x', 'y', 'latitude', 'longitude', 'all_pce_active_bus',
       'all_pde_active_bus', 'line_list', 'line_total_miles', 'load_list',
       'section_id', 'total_customers'],
      dtype='str')

In [7]:
trafo_df["bus_name"] = trafo_df["bus"].str.split(".").str[0]
count = 0

for bus in trafo_df["bus_name"]:
    bus_query = buses_df.query(f"name == '{bus}'")

    if bus_query.empty:
        print(bus + "\n")
        count += 1    

print(count)

0

In [10]:
display(trafo_df.query("name == 'trf_5557353a'"))

display(line_df)

display(buses_df.query("name == '82044325557353'"))

,name,phases,windings,wdg,bus,conn,kv,kva,tap,%r,...,bhflux,normamps,emergamps,faultrate,pctperm,repair,basefreq,enabled,like,bus_name
115,trf_5557353a,3,2,2,82044325557353.1.2.3.4,wye,0.38,75,1.05,0.67,...,[],3.4516,4.7067,0.007,100,36,60,true,,82044325557353

,name,bus1,bus2,linecode,length,phases,r1,x1,r0,x0,...,heightunit,conductors,normamps,emergamps,faultrate,pctperm,repair,basefreq,enabled,like
0,cmt_5281595,81463945002086.1.2.3,81463945002086b.1.2.3,,0.001,3,1,1,1,1,...,m,,400,600,0.1,20,3,60,true,
1,cmt_5286666,82034695002086.1.2.3,82034695002086b.1.2.3,,0.001,3,1,1,1,1,...,m,,400,600,0.1,20,3,60,true,
2,cmt_5286668,82034735002086.1.2.3,82034735002086b.1.2.3,,0.001,3,1,1,1,1,...,m,,400,600,0.1,20,3,60,true,
3,cmt_5286669,82044285002086.1.2.3,82044285002086b.1.2.3,,0.001,3,1,1,1,1,...,m,,400,600,0.1,20,3,60,true,
4,cmt_5286671,82054225002086.1.2.3,82054225002086b.1.2.3,,0.001,3,1,1,1,1,...,m,,400,600,0.1,20,3,60,true,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068,smt_88888869158,i888888516555002086.1.2.3,i888888516585002086.1.2.3,39-31m_3,1E-006,3,1.551,0.47,0.1784,0.4047,...,m,,125,600,0.1,20,3,60,true,
1069,smt_88888869403,84808465002086.1.2.3,i888888516545002086.1.2.3,39-31m_3,1E-006,3,1.551,0.47,0.1784,0.4047,...,m,,125,600,0.1,20,3,60,true,
1070,smt_53073787,82041975002086.1.2.3,82041965002086.1.2.3,33-31m_3,0.047869,3,0.975,0.47,0.1784,0.4047,...,m,,152,600,0.1,20,3,60,true,
1071,resist_mtr_trf_5286699a,82034475002086.2,mrt_82034475002086trf_5286699a.2,lc_mrt_trf_5286699a_1,0.001,1,15000,0,15000,0,...,m,,0,600,0.1,20,3,60,true,
1072,resist_mtr_trf_5286708a,82034845002086.2,mrt_82034845002086trf_5286708a.2,lc_mrt_trf_5286708a_1,0.001,1,15000,0,15000,0,...,m,,0,600,0.1,20,3,60,true,

,name,nodes,num_nodes,kv_base,distance,coord_defined,x,y,latitude,longitude,all_pce_active_bus,all_pde_active_bus,line_list,line_total_miles,load_list,section_id,total_customers
1189,82044325557353,"[1, 2, 3, 4]",4,0.219393,5.095354,1,-49.316464,-16.610318,0.0,0.0,"[Load.m2_trf_5557353a, Load.m1_trf_5557353a, R...",[Transformer.trf_5557353a],[None],0.0,"[LOAD.m2_trf_5557353a, LOAD.m1_trf_5557353a]",0,0

In [20]:
dss_tools.interactive_view.circuit_geoplot("active power")